# Architecture
arch: GraphMapResNet18

# ===== Dataset ===== #
data: dataset/
set: svhn
name: GraphMapResNet18

# ===== Learning Rate Policy ======== #
optimizer: adam
lr: 0.001
lr_policy: cosine_lr

# ===== Network training config ===== #
epochs: 100
weight_decay: 0 #0.0001
momentum: 0.9
batch_size: 256

# ===== Sparsity =========== #
init: kaiming_normal
nonlinearity: relu
scale_fan: True

# ===== Hardware setup ===== #
workers: 1
# ===== GraphMapMethod ===== #
message_type: Regular

# ===== GraphSet ===== #
nodes: 64
neighbors: 3
iter_num: 50